spring:
  application:
    name: nami-backend
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    jdbc-url: jdbc:postgresql://localhost:54320/namibackenddb
    username: namibackenddb
    password: namibackenddb
    driverClassName: org.postgresql.Driver
    type: "com.zaxxer.hikari.HikariDataSource"
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      register-mbeans: true
      validation-timeout: 3000
      jdbc-url: jdbc:postgresql://localhost:54320/namibackenddb